### ISSUE TITLE
AttributeError: module 'pelican-toc' has no attribute 'register'

### ISSUE THREAD

**Issue by floatovh** [ovh/docs-rendering#360]
Hello,

Running the container results in an empty directory listing with the following error in the logs : 
```
$ ./docker/run-container.sh -f $PATH -p $PORT
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.5.10
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `ovh_entities`
DEBUG: Registering plugin `ovh_entities`
DEBUG: Loading plugin `ovh_filters`
DEBUG: Registering plugin `ovh_filters`
DEBUG: Loading plugin `ovh_markdown`
DEBUG: Registering plugin `ovh_markdown`
DEBUG: Loading plugin `pelican-toc`
DEBUG: Registering plugin `pelican-toc`
CRITICAL: AttributeError: module 'pelican-toc' has no attribute 'register'
Traceback (most recent call last):
  File "/usr/local/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 393, in main
    pelican, settings = get_instance(args)
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 382, in get_instance
    return cls(settings), settings
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 53, in __init__
    self.init_plugins()
  File "/usr/local/lib/python3.5/site-packages/pelican/__init__.py", line 80, in init_plugins
    plugin.register()
AttributeError: module 'pelican-toc' has no attribute 'register'
```

**Comment by mayur-tolexo** [comment]
Hi Guys,
I am also getting same problem. Can you please help in solving this issue. 
Thanks.

**Comment by tbourrelovh** [comment]
Hi, this seems to be related to the fact that pelican-toc is a git submodule. Did you clone using the `--recursive` flag ?

If not, you can initialize the git submodules with the following command : 
```sh
git submodule update --init --recursive
```

**Comment by floatovh** [comment]
Hi, 

Thanks @tbourrelovh, it works !

Here is a proposal for updating the README accordingly : https://github.com/ovh/docs-rendering/pull/379
